### ISSUE TITLE
Strings in annotation such as Retrofit API is not obfuscated 

### ISSUE THREAD

**Issue by prituladima** [MichaelRocks/paranoid#10]
Strings in annotation such as Retrofit API is not obfuscated

**Comment by MichaelRocks** [comment]
Unfortunately, obfuscating strings in annotations is impossible. Annotations are stored as metadata so we cannot modify them programmatically at runtime.

**Comment by mayurdg93** [comment]
Hey @prituladima, you got any solution to obfuscate string in annotation?
