### ISSUE TITLE
Remove @Obfuscate on compile time

### ISSUE THREAD

**Issue by SamHoque** [MichaelRocks/paranoid#12]
I think it would be a good enhancement to remove the @Obfuscate tag in the annotated classes since it serves no purpose on runtime

**Comment by MichaelRocks** [comment]
@LynxKik I thought about that but I expect users of this library also to use some general purpose obfuscation tool like ProGuard that will remove the annotation. I can do that myself but is there any reason why you cannot remove the annotation with ProGuard?

**Comment by SamHoque** [comment]
Mostly I use this when I'm adding stuff to an app I am reverse engineering so I dont really call the classes and method, I just write them and compile them and then decompile them in dalvik. when i use proguard while doing this it will remove my classes since I am not using them.
