### ISSUE TITLE
Obfuscate don't work - Win7

### ISSUE THREAD

**Issue by nikolaGithub2018** [MichaelRocks/paranoid#13]
Hi,
In Windows7 the annotation @Obfuscate is not working for me. I compiled my project and decompiled with http://www.javadecompilers.com/apk, but no string is Obfuscate.
Tried on Win7 on both home and business pc, also tried with  release 0.1.6...

I am almost new to android, so maybe I made some silly mistake in gradle...do you mind take a look. ASAP :)

Thanks man... wishing all the best.

[proguard-rules.pro.txt](https://github.com/MichaelRocks/paranoid/files/1602735/proguard-rules.pro.txt)
[build.gradle ---module.txt](https://github.com/MichaelRocks/paranoid/files/1602736/build.gradle.---module.txt)
[build.gradle ---project.txt](https://github.com/MichaelRocks/paranoid/files/1602737/build.gradle.---project.txt)
[from gradle console.txt](https://github.com/MichaelRocks/paranoid/files/1602738/from.gradle.console.txt)
[gradle.properties.txt](https://github.com/MichaelRocks/paranoid/files/1602739/gradle.properties.txt)

[C0886e.java - decompiled.txt](https://github.com/MichaelRocks/paranoid/files/1602753/C0886e.java.-.decompiled.txt)

**Comment by MichaelRocks** [comment]
@nikolaGithub2018, which classes were marked with `@Obfuscate`? Currently there's [an issue](https://github.com/MichaelRocks/paranoid/issues/7) that prevents obfuscation of inner classes if their top-level class is marked with `@Obfuscate`. If you want you inner classes to be obfuscated you need to manually add `@Obfuscate` annotation to them.

**Comment by nikolaGithub2018** [comment]
It is not inner one.
In example from attachment it is class JedStanjaFragment which extends
Fragment...
I can send you all of my više but all strings and coments inside are on
serbian :) and project is not so small ...

четвртак, 04. јануар 2018., Michael Rozumyanskiy <notifications@github.com>
је написао/ла:

**Comment by MichaelRocks** [comment]
Yep, but which strings you want to be obfuscated? If they're in a nested class they won't be obfuscated until their class is annotated with `@Obfuscate`. It would be great if you can send me an original source file. Also I need a Gradle build log when you build your project with `--debug` flag. Please clean the project before that.

**Comment by nikolaGithub2018** [comment]
I apologise, did not figure out that (new TextWatcher(){} ) is inner class
too...braindead.
I heard braindead term few days ago and now I fully understand it.
First I will go to buy another pack of redbull, and when I come back I will
do whatever you want :)

Tell me how can I erase that issue posted on github (or mark it solved), or
do it yourself if that is convinient to you  -  Just tell me how to fix it.

At least I can do is to give you credits on github and in my own app_info
creditial...you name it.

Thanks.

oooooo to use @Obfuscate for listeners new classes, for example:

editText.addTextChangedListener( new TextWatcher(){
            @Override
            public void onTextChanged(CharSequence cs, int s, int b, int c){
                try {
                    var= Integer.parseInt(cs.toString());
                } catch (NumberFormatException e) {}

                if (var<-40||var>100){
                    var=40;
                    prikaziToast(getContext(),"Unesi var od -40 do 100");
                }
            }
            @Override
            public void beforeTextChanged(CharSequence cs, int s, int b,
int c){}
            @Override
            public void afterTextChanged(Editable e){}
        });
04.01.2018. 11.17, "Michael Rozumyanskiy" <notifications@github.com> је
написао/ла:

**Comment by MichaelRocks** [comment]
I will close this issue as a duplicate. As a workaround you can convert an anonymous class to an inner class (that is make it have a name) and annotate it with `@Obfuscate`.
