### ISSUE TITLE
How to use confusing .

### ISSUE THREAD

**Issue by Naguchennai** [MichaelRocks/paranoid#18]
How to use confusing  after i try as per ur example ... its not work
public static String myurl = "http://google.com";

after apk decompiler using http://www.javadecompilers.com/apk.. this url still showing in my decompiled files

**Comment by MichaelRocks** [comment]
Could you please show me your build.gradle file?

**Comment by Naguchennai** [comment]
apply plugin: 'com.android.application'
apply plugin: 'io.michaelrocks.paranoid'

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'io.michaelrocks:paranoid-gradle-plugin:0.2.4'
    }
}


android {
    compileSdkVersion 26
    defaultConfig {

**Comment by MichaelRocks** [comment]
May I ask you to build your project with `--debug` flag and attach build logs to the issue?

**Comment by santanusetu** [comment]
Make sure you are using @Obfuscate annotation on the class @naguchennai
