### ISSUE TITLE
Obfuscate don't work

### ISSUE THREAD

**Issue by abraaocaldas** [MichaelRocks/paranoid#2]
Hello there! 
In Windows the annotation @Obfuscate is not working. I compiled your sample and decompiled with dex2jar, here is the result.
![capturar](https://cloud.githubusercontent.com/assets/3661806/22184210/84fe3aee-e0a3-11e6-8f3c-a0eaec0deaa0.JPG)

**Comment by MichaelRocks** [comment]
I tried to compile the sample project on macOS and everything works just fine. Seems this is a Windows specific issue again. Could you please compile `sample` with `gradle clean :sample:assemble --info` and send me the build log?

**Comment by abraaocaldas** [comment]
Here is the log:
[debug.txt](https://github.com/MichaelRocks/paranoid/files/725084/debug.txt)

**Comment by MichaelRocks** [comment]
According to the log the library doesn't really work on Windows. Moreover, I tested it myself on a Windows machine and the bug reproduces. I'll try to understand why it happens.

**Comment by MichaelRocks** [comment]
@abraaocaldas I think I found the reason of this bug and will publish a hotfix today.
