### ISSUE TITLE
Allow to enable obfuscation for autogenerated BuildConfig class

### ISSUE THREAD

**Issue by gpinigin** [MichaelRocks/paranoid#20]
May be useful in case of several build configurations with different keys/addresses for every configuration

**Comment by MichaelRocks** [comment]
Actually if you obfuscate classes that use constants from `BuildConfig` and use a general purpose obfuscator like ProGuard or R8 your `BuildConfig` classes will be removed and strings from it will be obfuscated.

**Comment by gpinigin** [comment]
What kind of options should be enabled in ProGuard/R8 for that?

**Comment by MichaelRocks** [comment]
It should be removed if shrinking is enabled because all constants from `BuildConfig` are inlined to use sites during compilation.

**Comment by jutikorn** [comment]
@MichaelRocks  
For example, I have a class which contains a method that provide a value from BuildConfig like:
```
@Obfuscate
class MyHepler {
    fun getBuildConfigValue(): String {
         return BuildConfig.MY_CONSTANTS
      }
}
```
With `@Obfuscate` and Proguard, will this class got changed to this??

```
@Obfuscate
class b {
    fun a(): String {
         return Deobfuscator.getString(2)
      }
}
```

**Comment by jutikorn** [comment]
![image](https://user-images.githubusercontent.com/3265887/48598937-0d2aa700-e998-11e8-9e19-a98037639041.png)
I have just proved it by decompiled it with dex2-jar.
@MichaelRocks Thanks for a great tool
