### ISSUE TITLE
Paranoid does not obfuscate anything !

### ISSUE THREAD

**Issue by ICommandMachinesObey** [MichaelRocks/paranoid#24]
I used Paranoid for my project and I added @Obfuscate annotation, but whe I decompile the APK I see plain text , no obfuscation done ! I didn't see Paranoid Task in Gradle build, is that normal ?

**Comment by MichaelRocks** [comment]
Hi @ICommandMachinesObey,
I don't think that's normal. Could you attach your `build.gradle` file to the issue please?
