### ISSUE TITLE
Allows to disable obfuscation for the project

### ISSUE THREAD

**Issue by ICommandMachinesObey** [MichaelRocks/paranoid#25]
"_enabled — boolean. Allows to disable obfuscation for the project. Default value is true._" I think that the default value should be false.

**Comment by MichaelRocks** [comment]
Why? The purpose of the library is to obfuscate the project so the default behavior should be configuration-less if possible.

**Comment by MichaelRocks** [comment]
Obfuscation can be disabled using the following block:
```
paranoid {
  enabled false
}
```
