### ISSUE TITLE
Gradle build error

### ISSUE THREAD

**Issue by vidicunt** [MichaelRocks/paranoid#29]
Hello, my Gradle build crashes whenever using this library. Removing it fixed the issue.

Caused by: java.lang.ArrayIndexOutOfBoundsException

I am also using ProGuard 6.2.2

**Comment by MichaelRocks** [comment]
Hi @tommyzat and thank you for the report. Could you run the Gradle build with the follong command and send me `gradle.log` file:
```
./gradlew assembleDebug --info --stacktrace --console plain > gradle.log 2>&1
```
