### ISSUE TITLE
Deobfuscation - able to identify the strings

### ISSUE THREAD

**Issue by harikatam** [MichaelRocks/paranoid#30]
Step 1 reverse engineering.
step 2 Go to class file and get the string line Example - public static String eduScreenExpDate = Deobfuscator$app$Release.getString(6436);
Step 3 - Go to Deobfuscator$app$Release class file 
Deobfuscator$app$Release.java

Add this line in java file and run -   System.out.println("Value"+Deobfuscator$app$Release.getString(6377)); 
We are able to get values.
See we can add any proguard not to display this file

**Comment by MichaelRocks** [comment]
Hi @harikatam,

It's definitely possible to get deobfuscated strings if you patch application's bytecode. You should obfuscate the application with ProGuard/R8 to make it harder to deobfuscate.
