### ISSUE TITLE
Obfuscate on extension functions

### ISSUE THREAD

**Issue by DatL4g** [MichaelRocks/paranoid#39]
Let's say you extend the File class with an function which creates an intentChooser for it
Example: 
```kotlin
fun File.intentChooser(): Intent {
    val intent = Intent(Intent.ACTION_VIEW)
    intent.setDataAndType(Uri.fromFile(this), "text/plain")

    return Intent.createChooser(intent, "Choose App to open file")
}
```

Currently you can't obfuscate this using `@Obfuscate` because this works on classes only.
Would it be possible to enhance that, so `"text/plain"` and `"Choose App to open file"` can be obfuscated?

**Comment by MichaelRocks** [comment]
Hi @DATL4G,

Firstly, You can try and add `@file:Obfuscate` at the beginning of the file. Secondly, I'm working on a feature that will allow to specify classes to obfuscate without using an annotation (#23). Hope this feature is going to be ready soon.

**Comment by DATL4G** [comment]
Adding `@file:Obfuscate` doesn't work on top level functions as my example was also intended.
Sorry I forgot to mention this
