### ISSUE TITLE
Error while building Debug Apk

### ISSUE THREAD

**Issue by Faiyyaz** [MichaelRocks/paranoid#4]
Error:Execution failed for task ':app:transformClassesWithParanoidForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.ClassNotFoundException: android.location.Address

**Comment by MichaelRocks** [comment]
Could you please share some code where this bug reproduces?

**Comment by Faiyyaz** [comment]
Actually i m not getting any exact line number or in which file i m getting the error. It just pop up when i try to build release or debug apk

**Comment by MichaelRocks** [comment]
Is this an open source project? In case it's not, can you create a sample project where this bug reproduces? Anyway, it will be nice if you build your project with `--debug` and `--stacktrace` flags, and attach the build log to this issue.

```
./gradlew assembleDebug --debug --stacktrace > build.log 2>&1
```

**Comment by Faiyyaz** [comment]
It is not an open source project. It is my company project.

Thank you for your method i will try the same and revert you ASAP

**Comment by Faiyyaz** [comment]
![stacktrace2](https://cloud.githubusercontent.com/assets/18116236/25327267/2ee78e9e-28f1-11e7-939a-480515cf9f9c.png)
![stacktrace3](https://cloud.githubusercontent.com/assets/18116236/25327268/2eeec344-28f1-11e7-9ba7-12e06a93de8e.png)
![stacktrace4](https://cloud.githubusercontent.com/assets/18116236/25327269/2f044aac-28f1-11e7-9533-cbe9905822a0.png)
![stacktrace](https://cloud.githubusercontent.com/assets/18116236/25327270/2f04abb4-28f1-11e7-92b1-62ce3bc82154.png)
![stacktrace1](https://cloud.githubusercontent.com/assets/18116236/25327271/2f04b938-28f1-11e7-86bf-e3b805acc1ad.png)


Please check the stacktraces as request by you.
Thank you.

**Comment by MichaelRocks** [comment]
@Faiyyaz Thank you for the stacktrace. Please try the [new version](https://github.com/MichaelRocks/paranoid/releases/tag/v0.1.3).

**Comment by Faiyyaz** [comment]
Okk will try and let you know
Thank you for your help. It meant a lot to me

**Comment by Faiyyaz** [comment]
Thank you for your response.

We are very grateful to you.
Our app has been successfully build and thank you again for your help.
