### ISSUE TITLE
Bug: can't import project

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [MichaelRocks/paranoid#40]
Hello,

I wanted to have a look at this repository before using it on a real app.
I got this when I tried to open it:

![image](https://user-images.githubusercontent.com/5357526/96551534-1d054100-12bb-11eb-81e6-02d2de317545.png)

How come?

full log:

[log.txt](https://github.com/MichaelRocks/paranoid/files/5406848/log.txt)

**Comment by AndroidDeveloperLB** [comment]
It is easy to create a sample project though, like attached one:

[paranoidStringObfuscationSample.zip](https://github.com/MichaelRocks/paranoid/files/5408005/paranoidStringObfuscationSample.zip)

**Comment by MichaelRocks** [comment]
Hi @AndroidDeveloperLB,

Yep, I'm aware of this issue and it's already fixed in one of my branches. If you're still interested in manually building the project I can merge the fix into master.

**Comment by AndroidDeveloperLB** [comment]
I don't understand the offer, but if you say that you fixed it already, good :)

**Comment by MichaelRocks** [comment]
The issue should be fixed now.

**Comment by AndroidDeveloperLB** [comment]
@MichaelRocks Confirmed. Seems to work fine now. Not sure what the sample is supposed to show though. 
I suggest to edit the UI a bit, to show content before and after decoding.

**Comment by MichaelRocks** [comment]
@AndroidDeveloperLB It's impossible to achieve with the current implementation.

**Comment by AndroidDeveloperLB** [comment]
@MichaelRocks OK thank you.
