### ISSUE TITLE
Request: offer JNI "security layer" too

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [MichaelRocks/paranoid#41]
Instead of getting the strings from Java code, you could make it inside JNI, which is a bit harder to de-obfuscate...

**Comment by MichaelRocks** [comment]
I'm personally is not a big fan of native libraries because they sometimes fail to install properly and cause crashes in production. Maybe I'll consider moving obfuscation stuff into the native part but it's not going to happen soon.

**Comment by AndroidDeveloperLB** [comment]
It's just as an optional thing. It can help with a bit more security.
It's harder to de-obfuscate code in native than in Java/Kotlin, no?

**Comment by MichaelRocks** [comment]
Sure, I totally agree, but the implementation can be quite complicated and doubt I'll have enough time for that in the nearest future.

**Comment by AndroidDeveloperLB** [comment]
I might be wrong, but I think StringCare does it.
