### ISSUE TITLE
import paranoid whithout "com.android.application"

### ISSUE THREAD

**Issue by maalekj** [MichaelRocks/paranoid#44]
I have android module that doesn't have the line:

"apply plugin: 'com.android.application'"

when trying to apply paranoid I got the following error while syncing the gradle:

Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'io.michaelrocks.paranoid']
Caused by: org.gradle.api.GradleException: Paranoid plugin must be applied *AFTER* Android plugin

how to use paranoid without adding "com.android.application"

**Comment by MichaelRocks** [comment]
Do you want to use it for a non-Android module? Currently only Android modules are supported. If you want to use it in an Android app just apply the plugin to the app module.

**Comment by maalekj** [comment]
I found that what I have is a java library and not an android library or module.

thank you
