### ISSUE TITLE
Request: publish the repo to mavenCentral

### ISSUE THREAD

**Issue by Songroid** [MichaelRocks/paranoid#45]
From https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/, 
```
JFrog is making some important changes that will impact users of Bintray, JCenter (part of Bintray), GoCenter, and ChartCenter.
```

**Comment by AndroidDeveloperLB** [comment]
It's going to be removed, no?

https://www.reddit.com/r/androiddev/comments/lbssfn/now_that_bintray_and_jcenter_are_shutting_down/

**Comment by headsvk** [comment]
Is this project still maintained? We also use this library and want to continue when JCenter is down.

**Comment by MichaelRocks** [comment]
I'm moving my projects to Maven Central, and this one is the second in line.

**Comment by AndroidDeveloperLB** [comment]
@MichaelRocks Thank you very much!
Can you please write here when it moved?

**Comment by MichaelRocks** [comment]
@AndroidDeveloperLB Sure!

**Comment by valeriyo** [comment]
https://jcenter.bintray.com/ appears to have gone down :( and I can't build my app

**Comment by MichaelRocks** [comment]
@valeriyo I've already started moving Paranoid's dependencies so if everything goes fine I'll finish by the end of the week.

**Comment by AndroidDeveloperLB** [comment]
@MichaelRocks That's great! Thank you very much!

**Comment by AndroidDeveloperLB** [comment]
Why is it closed? Has it moved now? If so, please update the readme file of the repository (still says "jcenter")...

**Comment by MichaelRocks** [comment]
Yes, all the artifacts have been moved to Maven Central. Totally forgot about the readme, thank you @AndroidDeveloperLB.

**Comment by AndroidDeveloperLB** [comment]
@MichaelRocks Thank you very much!

**Comment by AndroidDeveloperLB** [comment]
@MichaelRocks This is also available, right:
```
implementation("io.michaelrocks:paranoid-core:0.3.2")
```
?

I ask because of this:
https://github.com/MichaelRocks/paranoid/issues/38

Or maybe it's not needed anymore?

**Comment by MichaelRocks** [comment]
@AndroidDeveloperLB Only `0.3.3` version is available in Maven Central. So you should add
```
implementation("io.michaelrocks:paranoid-core:0.3.3")
```

If you don't provide a valid pom.xml for your aar dependency the core dependency is still needed.

**Comment by AndroidDeveloperLB** [comment]
@MichaelRocks Right. Thank you very much!
So, it's still an important thing to use? Why isn't it mentioned on readme page of the repository?

**Comment by MichaelRocks** [comment]
@AndroidDeveloperLB It's an important thing if you don't publish your dependencies correctly. So that's not a problem with this particular project, that's why I don't mention it in readme.

**Comment by AndroidDeveloperLB** [comment]
@MichaelRocks Meaning it's for developers of libraries that use this repository?

**Comment by MichaelRocks** [comment]
I mean if developers distribute their libraries properly as maven dependencies with a correct pom.xml then the users of their libraries don't need to deal with the `paranoid-core` dependency themselves.

**Comment by AndroidDeveloperLB** [comment]
@MichaelRocks So, whether a developer works on a library that use this repository, or on a project that uses it directly, this dependency needs to be added.
So why not mention it on readme ?
It seems to be a very common requirement this way...

**Comment by MichaelRocks** [comment]
No, it doesn't need to be added in case everything is done right. I don't want to add it to readme because it's related to the process of publishing and distributing artifacts and not to the library.

**Comment by AndroidDeveloperLB** [comment]
@MichaelRocks What do you mean "done right"? If I create an app and need to use this repository, shouldn't I add this dependency?

**Comment by MichaelRocks** [comment]
No, you shouldn't. The dependency is added automatically by the plugin. And "done right" means that when you distribute an obfuscated aar it should come with a correct pom.xml that contains all the runtime dependencies including `paranoid-core`.

**Comment by AndroidDeveloperLB** [comment]
@MichaelRocks What if I have an app that uses paranoid, and I also use a library that uses paranoid (whether it's "done right" on it or not) ? Should I add the dependency or not?
And why not mention how library developers should use paranoid, as a side note, to make it "done right" ?

**Comment by MichaelRocks** [comment]
This is a general issue related to working with maven dependencies. Paranoid isn't different from any other library when you want to distribute an artifact that depends on it.

Anyway, I think we should stop discussing this stuff here because it's not related to the original issue. If you believe something has to be added to readme you could send me a PR.

**Comment by AndroidDeveloperLB** [comment]
ok sorry and thank you.
But can you please answer the question?

**Comment by AndroidDeveloperLB** [comment]
@MichaelRocks Here, a pull request as you told me:
https://github.com/MichaelRocks/paranoid/pull/47

**Comment by caiofaustino** [comment]
Hi, is it possible to also migrate the `0.3.2` version to Maven Central? I only see `0.3.3` available there.

**Comment by MichaelRocks** [comment]
@caiofaustino Hi, I would prefer not to migrate legacy versions.

**Comment by caiofaustino** [comment]
We have a library that uses your library and so it has `paranoid-core` as a transitive dependency. We migrated older versions as well so people using these older versions wouldn't be able to build their projects after JCenter is closed.

We will update to `0.3.3` on the next version but that doesn't solve the issue for people on older versions.

There are a few blog posts that could be helpful if you decide to migrate them, shouldn't be too complicated, and I would be happy with only migrating `0.3.2`, can be done manually in around 10 minutes :)

**Comment by caiofaustino** [comment]
Hi again @MichaelRocks, sorry to push but I just wanted to know if you would reconsider adding `0.3.2` to Maven Central or not. [This post](https://www.marcogomiero.com/posts/2021/move-libray-jcenter-to-maven/) has a nice easy approach to manually uploading them since it's just one version.

**Comment by MichaelRocks** [comment]
@caiofaustino I believe it won't solve problems caused by Bintray and jCenter shutdown but I'll do that.
