### ISSUE TITLE
Issue in new release

### ISSUE THREAD

**Issue by Faiyyaz** [MichaelRocks/paranoid#5]
![1 3stactrace](https://cloud.githubusercontent.com/assets/18116236/25333444/d0608c7e-2907-11e7-879d-77891505d4be.png)

I m getting the above error when i run the app & the app crashes

**Comment by MichaelRocks** [comment]
@Faiyyaz Could you please add a build log to this issue?
```
gradlew.bat assembleDebug --debug --stacktrace > build.txt 2>&1
```

**Comment by Faiyyaz** [comment]
[build.txt](https://github.com/MichaelRocks/paranoid/files/951431/build.txt)

Please find the attached text file of log as asked by you

**Comment by MichaelRocks** [comment]
Could you please collect logs for a clean build?
```
gradlew.bat clean assembleDebug --debug --stacktrace > build.txt 2>&1
```

**Comment by Faiyyaz** [comment]
[build.txt](https://github.com/MichaelRocks/paranoid/files/951449/build.txt)

Logs for a clean build

**Comment by MichaelRocks** [comment]
For some reason I don't see Paranoid transformation running. Could you show me contents of your `build.gradle` file?

**Comment by Faiyyaz** [comment]
![build1](https://cloud.githubusercontent.com/assets/18116236/25334510/74724c0e-290c-11e7-8f1c-3864a384d8d9.png)
![build](https://cloud.githubusercontent.com/assets/18116236/25334509/745ffaf4-290c-11e7-9163-62e6cd61f0c7.png)

Please find the build.gradle file contents

**Comment by MichaelRocks** [comment]
Your `build.gradle` looks correct to me. Does the sample project works for you?

**Comment by Faiyyaz** [comment]
I m working on my company project & i m not using the sample project if you want i can test the same and can revert back to you

**Comment by MichaelRocks** [comment]
It will be really great if you try and run the sample project in your environment.

**Comment by Faiyyaz** [comment]
I m trying will let you know

**Comment by Faiyyaz** [comment]
The sample is running in the device

So what is the solution for my project?

**Comment by Faiyyaz** [comment]
![stacktrace5](https://cloud.githubusercontent.com/assets/18116236/25337725/8fec9c10-291a-11e7-9e02-33e313b57bc7.png)

I m getting this stacktrace while building the debug apk

**Comment by Faiyyaz** [comment]
![stack](https://cloud.githubusercontent.com/assets/18116236/25337948/3ea5d910-291b-11e7-8966-97524983ad46.png)

I m getting this stacktrace while after removing nultidex from the project

**Comment by MichaelRocks** [comment]
@Faiyyaz Any chances I can get access to your project? Do you use the obfuscator only in the application project or in the library project too?

**Comment by MichaelRocks** [comment]
I have an idea how to fix a compilation bug. Will do that in several hours. But I don't think it will solve your problem.

**Comment by Faiyyaz** [comment]
I use only in app project

**Comment by Faiyyaz** [comment]
Ok will check the update and if that doesn't work then i will happily
provide you my code.

Thanks for your effort

On 24-Apr-2017 6:58 PM, "Michael Rozumyanskiy" <notifications@github.com>
wrote:

I have an idea how to fix a compilation bug. Will do that in several hours.
But I don't think it will solve your problem.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MichaelRocks/paranoid/issues/5#issuecomment-296667846>,
or mute the thread

**Comment by Faiyyaz** [comment]
I am sending you my code on your mail id using wetransfer please find the same and let me know when the error is resolved.

Thank you for your help

**Comment by MichaelRocks** [comment]
@Faiyyaz I fixed an error from your build logs. Could you please try and build your project again?

**Comment by Faiyyaz** [comment]
Ok i will try and let you know & i have sent you my code on paranoid email id using wetransfer. Did you check the same?

**Comment by MichaelRocks** [comment]
I installed WeTransfer but it says I should have received a link from you. Unfortunately, I don't see any links in my inbox.

**Comment by Faiyyaz** [comment]
I have send you the link yesterday on your paranoid id

**Comment by Faiyyaz** [comment]
Is the mentioned mail id in screenshot is correct or should i share
somewhere else

**Comment by MichaelRocks** [comment]
@Faiyyaz I'm not quite sure I understand what you mean by 'id in screenshot'. Please send a link to michael.rozumyanskiy@gmail.com.

**Comment by Faiyyaz** [comment]
Ok will send you the project now on the email id sent by you

**Comment by MichaelRocks** [comment]
@Faiyyaz Seems I managed to fix this issue. At least your project compiles fine and works on my device.

**Comment by Faiyyaz** [comment]
@Micheal Thanks a lot will try the updated version and let you know

**Comment by Faiyyaz** [comment]
Thanks a lot Micheal I have run the project just now it is working as required and the strings are also hidden on reverse engineering which i was needed.

Thanks alot once again for your help and effort and time as well.
