### ISSUE TITLE
ability to obfuscate BuildConfig contents

### ISSUE THREAD

**Issue by SajadGarshasbi** [MichaelRocks/paranoid#50]
Hi, is there any chance to obfuscate BuildConfig contents?

**Comment by MichaelRocks** [comment]
Hi @SajadGarshasbi, I have plans to add such functionality in #23 but cannot tell you when I have time to do that.

**Comment by iadcialim** [comment]
@MichaelRocks We store our secrets and api keys in `local.properties` so it wont be added in the repo. But they are added in the `BuildConfig` thru `build.gradle`. It would be good to obfuscate the strings there. Waiting for #23 
Thanks for this awesome lib again.
