### ISSUE TITLE
Could not initialize class io.michaelrocks.paranoid.grip.ClassesQueryBuilder

### ISSUE THREAD

**Issue by bassil-altamimi** [MichaelRocks/paranoid#51]
I'm unable to compile with version 0.3.3. I get the following error message.
Could not initialize class io.michaelrocks.paranoid.grip.ClassesQueryBuilder

**Comment by MichaelRocks** [comment]
Duplicates #49.

**Comment by MichaelRocks** [comment]
Hi @bassil-altamimi, it would be great if you add a comment to #49 and tell me what version of Kotlin and Gradle you use.
