### ISSUE TITLE
Please Port to Flutter

### ISSUE THREAD

**Issue by vaishakhpj** [MichaelRocks/paranoid#53]
Hi,
Can You Please port this plugin to flutter also.

Flutter is more safer to reverse engineering, but it produces a shared object as libapp.so, from which all the strings can be extracted, eg using the command strings libapp.so > extractedFile.txt in linux, by which all the strings used in app including the api keys will be revealed, it will be very useful if you port the plugin to dart language to use in flutter. This is the number one plugin used by all android devs in my company and most of the devs i know.

**Comment by MichaelRocks** [comment]
Hi @vaishakhpj,

Sorry, but that would be an absolutely different library. Taking into account the fact that I don't have any experience with Flutter it would be quite difficult for me to do that. And unfortunately I don't have free time to try. So I believe someone else has to do this job.

**Comment by vaishakhpj** [comment]
Ok, Anyway Thank You for creating this good plugin.
