### ISSUE TITLE
Where can i view version log?

### ISSUE THREAD

**Issue by tracer8** [MichaelRocks/paranoid#55]
Hi, 
When i'm trying to use version 0.3.3, it generate some error when build, so i must downgrade to 0.3.2.
Can i have some verion log to view what change between every versions?
Thanks!

**Comment by MichaelRocks** [comment]
Hi, please take a look at #49. I believe you have to update Gradle to 6.8 or later. And unfortunately there's no version log.

**Comment by tracer8** [comment]
Yes, i saw it before, so i decide to downgrade to 0.3.2.
But what happen with 0.3.3, did it have any important upgrade?

**Comment by MichaelRocks** [comment]
In 0.3.3 I moved artifacts from Jcenter to Maven Central, and in order to do that I had to update dependencies including Gradle. Nothing in the obfuscation part has changed.

**Comment by tracer8** [comment]
Oh, ok thank you so much!

**Comment by MichaelRocks** [comment]
You're welcome!
