### ISSUE TITLE
Problem with generate artifac in component use paranoid

### ISSUE THREAD

**Issue by romnyd** [MichaelRocks/paranoid#56]
implement the paranoid component in a component. The idea is to generate an artifact to use in another component. 

* What went wrong:
A problem occurred evaluating root project 'document_xxxxx'.
> Failed to apply plugin 'io.michaelrocks.paranoid'.
   > Paranoid plugin must be applied *AFTER* Android plugin

**Comment by MichaelRocks** [comment]
Are you trying to use Paranoid in a non-Android module? Currently it's not supported.
