### ISSUE TITLE
I want to hide Deobfuscator on Reverse Engineering

### ISSUE THREAD

**Issue by Faiyyaz** [MichaelRocks/paranoid#6]
![deobfuscator](https://cloud.githubusercontent.com/assets/18116236/25424133/e0217442-2a84-11e7-8155-0569a9d04e94.png)

I want to hide your deobfuscator class because if i didn't do it then everybody will be able to decode the string used in my project using the array return in the class.

So please help me and sorry for the disturbance.

**Comment by MichaelRocks** [comment]
@Faiyyaz The best approach would be to use a code obfuscator like ProGuard.

**Comment by Faiyyaz** [comment]
I m using the same but it just changes the class name to something else and i can guess the encryption and break it.

And if you have any prograud example file can you share the same with me if possible where all the strings get hidden on reverse engineering

**Comment by MichaelRocks** [comment]
Unfortunately there's no way to hide obfuscated strings so that they cannot be deobfuscated. The idea is simple: if your app can deobfuscate strings, why somebody else cannot? So the best thing you can do is to make obfuscated string harder to find in decompliled code.

**Comment by Faiyyaz** [comment]
Can you provide me some help or example of proguard which you may have used in your projects?

**Comment by MichaelRocks** [comment]
I recommend you to start with this tutorial: https://developer.android.com/studio/build/shrink-code.html

You should set `minifyEnabled true` in `build.gradle` but probably you'll face some ProGuard-related bugs.

**Comment by Faiyyaz** [comment]
I have done the same in my project but the hardcoded string is still
visible as before that's why i was using your library thinking that it can
do the encryption part

**Comment by MichaelRocks** [comment]
Yep, ProGuard doesn't obfuscate strings but if you obfuscate your strings with Paranoid and then obfuscate the app with ProGuard original strings shouldn't be visible anymore.

**Comment by Faiyyaz** [comment]
You are extremely right Micheal but the thing is as you can see in the screenshot attached in the issue the thing is on reverse engineering anyone can compile the string using deofuscator class

**Comment by MichaelRocks** [comment]
But if `Deobfuscator` class is obfuscated by ProGuard it becomes much harder to find. How do you think obfuscated strings should look like so nobody can deobfuscate them?

**Comment by Faiyyaz** [comment]
Hmm i know you are right at your side but i want like suppose there is a login page where i have param key "mobile" so it should be change to some string which is not readable on reverse engineering

**Comment by MichaelRocks** [comment]
That's exactly what will happen if you process your project with Paranoid. There will be no hardcoded strings. Instead you'll see calls to `Deobfuscator` with some integer arguments. However, if someone wants to deobfuscate those strings and puts enough effort into reverse engineering of your app she'll be able to do that.

**Comment by Faiyyaz** [comment]
Yes thank you for the time and your help and everything.

**Comment by harikatam** [comment]
Sorry to write it now - but i was checking if we can rename the deobfuscator class using proguard in your plugin - which will be harder to find the class
