### ISSUE TITLE
Query: Need Help on Some Queries related to this library. Please assit.

### ISSUE THREAD

**Issue by shrishkukde** [MichaelRocks/paranoid#63]
Hello Team,

I need to use this library in a production application which has a user base of millions of users.
I have following queries and some simple doubts:
I respect you all so please do not take my questions otherwise, I am a beginner and some questions can be very basic, please consider me.

0. Can I use this library for production application to obfuscate strings
1. Tis library is in Kotlin, but will it support Java Android App
1. Will this library be maintained in future (at least for next 10 years)
2. If I face any challenge/crash then will I receive timely support/help
3. What if this library gets removed from GitHub due to some reasons, then what impact it will have to my application
4. What impact it will have to my application, if this library is no longer maintained.
5. How this library works?

**Comment by MichaelRocks** [comment]
Hi @shrishkukde,

0. This library is used in an app with a few million DAU, and it has never caused any issues.
1. At this point the library hypothetically can be used with any JVM-based language.
2. There're absolutely no warrantees regarding long-term support and any other support, but it's open-sourced, so you can fork it in case of emergency.
3. Once again no warranties, but if the issue will seem critical to me I'll fix it.
4. I don't think it will be removed but its source code is published on Maven Central along with the built artifacts, so you'll be able to get sources from there. And nothing can be removed from Maven Central.
5. Your application might stop building but you can remove the plugin from build.gradle files and fix the build. However in this case you'll lose obfuscation.
6. It uses Android Transform API and patches application's bytecode replacing string literals with some other code.

**Comment by shrishkukde** [comment]
Hi @MichaelRocks 
Thank you very much for your response. This is really helpful.
Thank a lot.
