### ISSUE TITLE
paranoid was not found in any of the following sources

### ISSUE THREAD

**Issue by mohamad62** [MichaelRocks/paranoid#72]
Can anyone help to solve this problem

`Plugin [id: 'io.michaelrocks.paranoid', version: '0.3.7', apply: false] was not found in any of the following sources:

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'io.michaelrocks.paranoid', version: '0.3.7', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'io.michaelrocks.paranoid:io.michaelrocks.paranoid.gradle.plugin:0.3.7')
  Searched in the following repositories:
    Gradle Central Plugin Repository
    Google
    MavenRepo`

**Comment by kkkasio** [comment]
Do hou have an solution?
I have same problem!
<img width="1608" alt="Screenshot 2024-07-17 at 14 12 44" src="https://github.com/user-attachments/assets/f4905053-5e64-441e-8793-96b5e829c829">


but its show code 401 🤔 from jitpack
